namespace Dashing.Tests.Configuration {
    using Dashing.Configuration;
    using Dashing.Tests.TestDomain;

    using Xunit;

    public class DefaultConventionTests {
        [Fact]
        public void DefaultTableNameIsThePlural() {
            var target = this.MakeTarget();
            Assert.Equal("Posts", target.TableFor(typeof(Post)));
        }

        [Fact]
        public void DefaultSchemaIsNull() {
            var target = this.MakeTarget();
            Assert.Null(target.SchemaFor(typeof(Post)));
        }

        [Fact]
        public void IdIsPK() {
            var target = this.MakeTarget();
            Assert.True(target.IsPrimaryKeyFor(typeof(Post), "id"));
        }

        [Fact]
        public void CaseInsensitiveIdIsPK() {
            var target = this.MakeTarget();
            Assert.True(target.IsPrimaryKeyFor(typeof(Post), "ID") && target.IsPrimaryKeyFor(typeof(Post), "id"));
        }

        [Fact]
        public void EntityNamePlusIdIsPK() {
            var target = this.MakeTarget();
            Assert.True(target.IsPrimaryKeyFor(typeof(Post), "PostId"));
        }

        [Fact]
        public void EntityNamePlusIdIsPKNotCaseinsensitive() {
            var target = this.MakeTarget();
            Assert.False(target.IsPrimaryKeyFor(typeof(Post), "postid"));
        }

        [Fact]
        public void DefaultsToAutoGeneratedPrimaryKeys() {
            var target = this.MakeTarget();
            Assert.True(target.IsPrimaryKeyAutoGenerated(typeof(Post)));
        }

        [Fact]
        public void DefaultStringLengthIs255() {
            var target = this.MakeTarget();
            Assert.Equal(255, target.StringLengthFor(typeof(Post), null));
        }

        [Fact]
        public void DefaultDecimalPrecisionIs18() {
            var target = this.MakeTarget();
            Assert.Equal(18, target.DecimalPrecisionFor(typeof(Post), null));
        }

        [Fact]
        public void DefaultDecimalScaleIs10() {
            var target = this.MakeTarget();
            Assert.Equal(10, target.DecimalScaleFor(typeof(Post), null));
        }

        private DefaultConvention MakeTarget() {
            return new DefaultConvention();
        }
    }
}