namespace TopHat.Configuration
{
    public interface IConfiguration
    {
        /// <summary>
        /// If set to true will always return tracked entities from queries
        /// </summary>
        bool AlwaysTrackEntities { get; set; }

        /// <summary>
        /// Indicates that primary keys are generated by the database by default
        /// </summary>
        /// <remarks>Can be individually overridden</remarks>
        bool PrimaryKeysDatabaseGeneratedByDefault { get; set; }

        /// <summary>
        /// Indicates that all foreign keys will have indexes generated on them to aid performance
        /// </summary>
        bool GenerateIndexesOnForeignKeysByDefault { get; set; }

        /// <summary>
        /// Specifies the default schema name
        /// </summary>
        string DefaultSchema { get; set; }

        /// <summary>
        /// The object to table mappings
        /// </summary>
        IMapping Mapping { get; }

        /// <summary>
        /// Run the configuration
        /// </summary>
        Mapper.Mapper Configure();
    }
}