using System;
using System.Collections.Generic;
using TopHat.Configuration.Mapper;

namespace TopHat.Configuration
{
    public interface IConfiguration
    {
        /// <summary>
        /// If set to true will always return tracked entities from queries
        /// </summary>
        bool AlwaysTrackEntities { get; set; }

        /// <summary>
        /// Indicates that primary keys are generated by the database by default
        /// </summary>
        /// <remarks>Can be individually overridden</remarks>
        bool PrimaryKeysDatabaseGeneratedByDefault { get; set; }

        /// <summary>
        /// Indicates that all foreign keys will have indexes generated on them to aid performance
        /// </summary>
        bool GenerateIndexesOnForeignKeysByDefault { get; set; }

        /// <summary>
        /// If true all table names that aren't explicity set will be pluralised according to english rules
        /// </summary>
        bool PluraliseNamesByDefault { get; set; }

        /// <summary>
        /// Specifies the default decimal precision
        /// </summary>
        int DefaultDecimalPrecision { get; set; }

        /// <summary>
        /// Specifies the default decimal scale
        /// </summary>
        int DefaultDecimalScale { get; set; }

        /// <summary>
        /// Specifies the default string length
        /// </summary>
        int DefaultStringLength { get; set; }

        /// <summary>
        /// Specifies the default schema name
        /// </summary>
        string DefaultSchema { get; set; }

        /// <summary>
        /// The object to table mappings
        /// </summary>
        IDictionary<Type, IMap> Maps { get; }

        /// <summary>
        /// Run the configuration
        /// </summary>
        IConfiguration Configure();

        IConfiguration Add(Type type);

        IConfiguration Add<T>();

        IConfiguration Add(IEnumerable<Type> types);

        EntityMapper<T> Setup<T>();

        IConfiguration AddNamespace(string nameSpace);
    }
}