using System;

namespace TopHat.Configuration {
	public interface IConvention {
		/// <summary>
		///   Identifies the table name for an entity type
		/// </summary>
		String TableFor(Type entity);

		/// <summary>
		///   Identifies the schema name for an entity type (if specified, else null for the default schema)
		/// </summary>
		String SchemaFor(Type entity);

		/// <summary>
		///   Identifies the primary key name for a given entity
		/// </summary>
		String PrimaryKeyOf(Type entity);

		/// <summary>
		///   Identifies whether the primary key is auto-generated for a given entity
		/// </summary>
		Boolean IsPrimaryKeyAutoGenerated(Type entity);

		/// <summary>
		///   Specifies the string length for a property
		/// </summary>
		ushort StringLengthFor(Type entity, String propertyName);

		/// <summary>
		///   Specifies the decimal precision for a property
		/// </summary>
		byte DecimalPrecisionFor(Type entity, String propertyName);

		/// <summary>
		///   Specifies the decimal scale for a property
		/// </summary>
		byte DecimalScaleFor(Type entity, String propertyName);
	}
}