namespace Dashing.Tools.Migration {
    using Dashing.Configuration;

    public class MigrationPair {
        public IMap From { get; private set; }

        public IMap To { get; private set; }

        public bool RequiresUpdate() {
            if (this.From.Columns.Count != this.To.Columns.Count) {
                return true;
            }

            foreach (var pair in this.From.Columns) {
                var fc = pair.Value;
                var tc = this.To.Columns[pair.Key];

                if (tc == null) {
                    return true;
                }

                if (fc.DbName != tc.DbName
                    || fc.DbType != tc.DbType
                    || fc.IsAutoGenerated != tc.IsAutoGenerated
                    || fc.IsNullable != tc.IsNullable
                    || fc.IsPrimaryKey != tc.IsPrimaryKey
                    || fc.Length != tc.Length
                    || fc.Precision != tc.Precision
                    || fc.Scale != tc.Scale) {
                    return true;
                }
            }

            return false;
        }

        public static MigrationPair Of(IMap from, IMap to) {
            return new MigrationPair { From = @from, To = to };
        }
    }
}