namespace Dashing.SchemaReading {
    class SqlServerSchemaReader : BaseSchemaReader {
        protected override string GetForeignKeySql(string databaseName) {
            return @"SELECT  tab1.name AS [TableName],
    obj.name AS Name,
    col1.name AS [ColumnName],
    tab2.name AS [ReferencedTableName],
    col2.name AS [ReferencedColumnName]
FROM sys.foreign_key_columns fkc
INNER JOIN sys.objects obj
    ON obj.object_id = fkc.constraint_object_id
INNER JOIN sys.tables tab1
    ON tab1.object_id = fkc.parent_object_id
INNER JOIN sys.schemas sch
    ON tab1.schema_id = sch.schema_id
INNER JOIN sys.columns col1
    ON col1.column_id = parent_column_id AND col1.object_id = tab1.object_id
INNER JOIN sys.tables tab2
    ON tab2.object_id = fkc.referenced_object_id
INNER JOIN sys.columns col2
    ON col2.column_id = referenced_column_id AND col2.object_id = tab2.object_id";
        }

        protected override string GetIndexSql() {
            return @"SELECT 
     TableName = t.name,
     Name = ind.name,
     ColumnName = col.name,
     ColumnId = ic.index_column_id,
     IsUnique = ind.is_unique
FROM 
     sys.indexes ind 
INNER JOIN 
     sys.index_columns ic ON  ind.object_id = ic.object_id and ind.index_id = ic.index_id 
INNER JOIN 
     sys.columns col ON ic.object_id = col.object_id and ic.column_id = col.column_id 
INNER JOIN 
     sys.tables t ON ind.object_id = t.object_id 
WHERE 
     ind.is_primary_key = 0 
     AND ind.is_unique_constraint = 0 
     AND t.is_ms_shipped = 0 
ORDER BY 
     t.name, ind.name, ind.index_id, ic.index_column_id ";
        }

        protected override string GetColumnSql() {
            return @"select col.TABLE_NAME AS TableName
     , col.COLUMN_NAME AS Name
     , col.ORDINAL_POSITION AS OrdinalPosition
     , col.DATA_TYPE AS DbTypeName
	 , col.NUMERIC_PRECISION as [Precision]
	 , col.NUMERIC_SCALE as Scale
     , case when col.CHARACTER_MAXIMUM_LENGTH = -1 then 1 else 0 end AS MaxLength
     , col.CHARACTER_MAXIMUM_LENGTH as Length
     , col.COLUMN_DEFAULT AS [Default]
     , col.DATETIME_PRECISION AS DatePrecision
     , CAST(CASE col.IS_NULLABLE
                WHEN 'NO' THEN 0
                ELSE 1
            END AS bit) AS IsNullable
     , COLUMNPROPERTY(OBJECT_ID('[' + col.TABLE_SCHEMA + '].[' + col.TABLE_NAME + ']'), col.COLUMN_NAME, 'IsIdentity')AS IsAutoGenerated
     , CAST(ISNULL(pk.is_primary_key, 0)AS bit) AS IsPrimaryKey
  FROM INFORMATION_SCHEMA.COLUMNS AS col
       LEFT JOIN ( SELECT SCHEMA_NAME(o.schema_id) AS TABLE_SCHEMA
                      , o.name AS TABLE_NAME
                      , c.name AS COLUMN_NAME
                      , i.is_primary_key
                   FROM sys.indexes AS i JOIN sys.index_columns AS ic ON i.object_id = ic.object_id
                                                                     AND i.index_id = ic.index_id
                                         JOIN sys.objects AS o ON i.object_id = o.object_id
                                         LEFT JOIN sys.columns AS c ON ic.object_id = c.object_id
                                                                   AND c.column_id = ic.column_id
                  WHERE i.is_primary_key = 1) pk ON col.TABLE_NAME = pk.TABLE_NAME
                                                  AND col.TABLE_SCHEMA = pk.TABLE_SCHEMA
                                                  AND col.COLUMN_NAME = pk.COLUMN_NAME
 ORDER BY col.TABLE_NAME, col.ORDINAL_POSITION;";
        }
    }
}